from contextlib import contextmanager
from pathlib import Path
from typing import Generator

from sqlmodel import Session, SQLModel, create_engine, select

from .config import get_settings


settings = get_settings()


def _prepare_sqlite_path(db_url: str) -> None:
    if db_url.startswith("sqlite"):
        # sqlite:///./data/data.db -> extract local path after third slash
        raw_path = db_url.split("sqlite:///")[-1]
        path = Path(raw_path)
        if not path.is_absolute():
            path = Path.cwd() / path
        path.parent.mkdir(parents=True, exist_ok=True)


_prepare_sqlite_path(settings.database_url)

connect_args = (
    {"check_same_thread": False} if settings.database_url.startswith("sqlite") else {}
)
engine = create_engine(settings.database_url, echo=False, connect_args=connect_args)


def seed_event_options(session: Session) -> None:
    """Seed a minimal set of event options per region if missing."""
    from app.models import (
        EventOption,
        EventCategory,
    )  # local import to avoid circular deps

    legacy_image_fixes = {
        "https://images.unsplash.com/photo-1518609559197-2a6c2f3b9c4f?w=600": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1502844521879-c88f28c5e62f?w=600": "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1522204781483-3c9f22030d9e?w=600": "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1549429532-680c2f21a4f0?w=600": "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1518621743603-f32a0d1d3c2a?w=600": "https://images.unsplash.com/photo-1527169402691-feff5539e52c?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1517646549293-1b2c4d7d9e4a?w=600": "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1551690025-a6e5a6f2b7b5?w=600": "https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1558229988-c9c0f9b6e6f4?w=600": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1502476100147-3860d5b5b0d0?w=600": "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=1200&q=80",
    }

    fixes_applied = False
    for old_url, new_url in legacy_image_fixes.items():
        matches = session.exec(
            select(EventOption).where(EventOption.image_url == old_url)
        ).all()
        for event in matches:
            event.image_url = new_url
            fixes_applied = True

    if fixes_applied:
        session.commit()

    seeds_by_region = {
        "OOE": [
            dict(
                title="Masters of Escape: Team-Rätselspaß in Linz",
                category=EventCategory.action,
                tags=["escape-game", "teambuidling", "puzzle"],
                location_region="OOE",
                est_price_pp=28,
                min_participants=8,
                accessibility_flags=["wheelchair"],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Teamstärkende Rätsel, Spannung, Kooperation, unvergesslicher Spaß.",
                long_description="Adrenalin, Teamgeist und Rätselspaß: In dieser Escape Room Challenge wachst Ihr als Team zusammen, kommuniziert besser und feiert gemeinsam den Erfolg.",
                physical_intensity=2,
                mental_challenge=5,
                social_interaction_level=5,
                price_comment="Reine Spielgebühr ca. 25–30 € p.P. (je nach Teamgröße); bei mehreren Räumen gleichzeitig oft Rabatte auf Anfrage.",
                external_rating=4.9,
                lead_time_min_days=7,
                risk_level="low",
                travel_time_from_office_minutes=5,
                address="Kaarstraße 9, 4040 Linz",
                website="https://www.mastersofescape.at",
                provider="Masters of Escape GmbH",
                phone="0732272999",
                email="office@mastersofescape.at",
            ),
            dict(
                title="Lasertron: Actionreiches Lasertag Battle",
                category=EventCategory.action,
                tags=["lasertag", "action", "teambuilding", "indoor"],
                location_region="OOE",
                est_price_pp=22,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Actionreicher Lasertag-Spaß für Teams mit Strategie, Adrenalin und viel Bewegung.",
                long_description="In der futuristischen Lasertag-Arena tretet ihr in Teams gegeneinander an, trainiert Taktik, Reaktion und Kommunikation – perfekt, um Kolleg:innen spielerisch zusammenzuschweißen.",
                physical_intensity=5,
                mental_challenge=2,
                social_interaction_level=3,
                price_comment="Pakete (z.B. 3 Spiele + Getränk) liegen bei ca. 22 €; Exklusivmiete der Arena für Firmenfeiern möglich.",
                external_rating=4.3,
                risk_level="medium",
                travel_time_from_office_minutes=5,
                address="Prinz-Eugen-Straße 22, 4020 Lustenau",
                website="https://lasertron-linz.at/",
                provider="Lasertron Linz",
                phone="0732946227",
                email="info@lasertron-linz.at",
            ),
            dict(
                title="Exit the Room: Das Escape Abenteuer Linz",
                category=EventCategory.action,
                tags=["escape-room", "rätsel", "teambuilding", "indoor"],
                location_region="OOE",
                est_price_pp=28,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Klassische Escape Rooms mit kniffligen Rätseln und 60 Minuten Zeitdruck.",
                long_description="Ihr werdet gemeinsam in einen Themenraum „eingesperrt“ und müsst innerhalb von 60 Minuten Codes knacken, Hinweise kombinieren und als Team den Ausweg finden – ideal für kleine Gruppen, die Grübelspaß lieben.",
                physical_intensity=2,
                mental_challenge=5,
                social_interaction_level=5,
                price_comment="Preis sinkt bei voller Belegung (6 Pers.) auf ca. 22 € p.P.; reine Spielkosten, keine Gastronomie vor Ort.",
                external_rating=4.7,
                risk_level="low",
                travel_time_from_office_minutes=5,
                address="Auerspergstraße 15, 4020 Linz",
                website="https://www.exittheroom.at/escape-room-linz",
                provider="Exit the Room Linz",
                phone="06606844996",
                email="linz@exittheroom.at",
            ),
            dict(
                title="NoWayOut: Premium Escape Room Erlebnis",
                category=EventCategory.action,
                tags=["escape-room", "horror", "rätsel", "teambuilding"],
                location_region="OOE",
                est_price_pp=30,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Filmreife Escape-Abenteuer mit starken Storys und viel Adrenalin.",
                long_description="Aufwendig gestaltete Themenräume sorgen für Gänsehaut, Spannung und Teamwork – von magischen bis schaurigen Szenarien arbeitet ihr euch gemeinsam durch Rätsel, Effekte und Überraschungen.",
                physical_intensity=2,
                mental_challenge=5,
                social_interaction_level=5,
                price_comment="Premium-Räume liegen bei ca. 30–35 € p.P.; spezielle Firmen-Challenge-Modi für große Gruppen buchbar.",
                external_rating=4.4,
                risk_level="low",
                travel_time_from_office_minutes=5,
                address="Prinz-Eugen-Straße 22, 4020 Lustenau",
                website="https://linz.nowayout-escape.at/de/",
                provider="NoWayOut Linz",
                phone="0732946227",
                email="linz@nowayout-escape.at",
            ),
            dict(
                title="Ocean Park: Bowling & Dinner Teamevent",
                category=EventCategory.action,
                tags=["bowling", "essen", "trinken", "fun", "indoor", "teambuilding"],
                location_region="OOE",
                est_price_pp=35,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Bowling, Games und Gastronomie im großen Family-Entertainment-Center.",
                long_description="Zwischen Bowlingbahnen, Billard und Arcade-Games stärkt ihr euch mit Drinks und Speisen – lockere Atmosphäre für entspannte Firmenfeiern, Afterwork-Events und größere Gruppen.",
                physical_intensity=3,
                mental_challenge=2,
                social_interaction_level=4,
                price_comment="Reine Bahnmiete ist günstig (geteilt durch Spieler); beliebtes \"Eat & Bowl\"-Paket (Burger + Bowling) liegt bei ca. 30–40 € p.P.",
                external_rating=3.5,
                risk_level="low",
                travel_time_from_office_minutes=14,
                address="Plus-Kauf-Straße 7, 4061 Pasching",
                website="https://oceanparkpluscity.at/",
                provider="Ocean Park GmbH",
                phone="0722962222",
                email="linz@oceanpark.at",
            ),
            dict(
                title="JUMP DOME Linz: Trampolin-Action pur",
                category=EventCategory.action,
                tags=["trampolinpark", "action", "sport", "teambuilding", "indoor"],
                location_region="OOE",
                est_price_pp=24,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Großer Trampolin- und Funpark für körperliche Action und Auspowern im Team.",
                long_description="Auf zahlreichen Trampolinen, Parcours und Sprungelementen könnt ihr euch so richtig austoben, gemeinsam Challenges meistern und spielerisch Teamgeist, Balance und Mut trainieren.",
                physical_intensity=5,
                mental_challenge=1,
                social_interaction_level=3,
                price_comment="Business-Pakete (Eintritt, Socken, Getränk, Snack) starten ab ca. 24 €; Catering für danach zubuchbar.",
                external_rating=4.6,
                risk_level="high",
                travel_time_from_office_minutes=13,
                address="Im Bäckerfeld 1, 4060 Leonding",
                website="https://jumpdome.at/linz/",
                provider="JUMP DOME Linz GmbH",
                phone="0732600600",
                email="linz@jumpdome.at",
            ),
            dict(
                title="Linzer Bier: Brauereiführung & Verkostung",
                category=EventCategory.food,
                tags=["führung", "brauerei", "bier", "genuss", "teambuilding", "kultur"],
                location_region="OOE",
                est_price_pp=19,
                min_participants=8,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Geführter Rundgang durch die Linzer Brauerei mit Blick hinter die Kulissen und Verkostung.",
                long_description="Ihr taucht in die Geschichte des Linzer Biers und der Tabakfabrik ein, lernt den Brauprozess kennen und schließt die Tour mit einer gemütlichen Bierverkostung – perfekt für genussorientierte Teams.",
                physical_intensity=2,
                mental_challenge=1,
                social_interaction_level=3,
                price_comment="Basis-Führung inkl. Kostprobe ca. 16–19 €; mit ausgiebiger Jause/Verkostung eher 25–30 € p.P.",
                external_rating=4.3,
                risk_level="low",
                travel_time_from_office_minutes=5,
                address="Peter-Behrens-Platz 1, 4020 Linz",
                website="https://www.linzerbier.at/fuehrungen/",
                provider="Linzer Bierbrauerei",
                phone="0732797800",
                email="office@linzerbier.at",
            ),
            dict(
                title="Ruff Indoor Golf: Die Team-Challenge Linz",
                category=EventCategory.action,
                tags=["indoor-golf", "sport", "fun", "teambuilding"],
                location_region="OOE",
                est_price_pp=25,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Modernes Indoor-Golf mit Simulatoren für Anfänger:innen und Pros.",
                long_description="In Lounge-Atmosphäre spielt ihr virtuelle Golfplätze rund um den Globus, probiert unterschiedliche Challenges aus und könnt euch bei Drinks in Ruhe austauschen – ein lockeres, wetterunabhängiges Teamevent.",
                physical_intensity=3,
                mental_challenge=1,
                social_interaction_level=3,
                price_comment="Box-Miete wird durch Spieler geteilt (günstig); Event-Pakete inkl. Drinks & Snacks starten meist ab 25 € p.P.",
                external_rating=4.8,
                risk_level="low",
                travel_time_from_office_minutes=14,
                address="Im Bäckerfeld 1/Parkhaus 2. OG, 4060 Leonding",
                website="https://ruffgolf.eu/at/",
                provider="RUFF Indoor Golf",
                phone="06764600234",
                email="linz@ruffgolf.at",
            ),
            dict(
                title="Another World: VR Team-Abenteuer erleben",
                category=EventCategory.action,
                tags=["virtual-reality", "gaming", "action", "teambuilding", "indoor"],
                location_region="OOE",
                est_price_pp=35,
                min_participants=35,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Kooperative VR-Missionen auf großer Spielfläche – gemeinsam in die virtuelle Welt eintauchen.",
                long_description="Mit VR-Brillen und voller Bewegungsfreiheit erlebt ihr packende Teamspiele, löst Aufgaben im virtuellen Raum und stärkt nebenbei Reaktion, Kommunikation und Zusammenspiel.",
                physical_intensity=4,
                mental_challenge=2,
                social_interaction_level=4,
                price_comment="Spielsession kostet ca. 30–40 € p.P.; Lounge für Feiern kann exklusiv dazu gemietet werden.",
                external_rating=5.0,
                risk_level="medium",
                travel_time_from_office_minutes=10,
                address="Wegscheider Str. 22, 4020 Linz",
                website="https://linz.another-world.com/",
                provider="Another World VR",
                phone="06641530932",
                email="linz@another-world.com",
            ),
            dict(
                title="Deep Space 8K: Zukunftstrip im AEC Linz",
                category=EventCategory.relax,
                tags=["technik", "innovation", "kultur", "multimedia", "indoor"],
                location_region="OOE",
                est_price_pp=15,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Immersive 8K-Projektionen auf Wand und Boden – digitale Welten in Riesendimension.",
                long_description="Im Deep Space 8K erlebt ihr spektakuläre Visualisierungen, interaktive Inhalte und Wissensshows – ideal für Teams, die sich für Technologie, Kunst und Zukunftsthemen begeistern.",
                physical_intensity=2,
                mental_challenge=2,
                social_interaction_level=3,
                price_comment="Gruppeneintritt + Highlightführung ca. 15 € p.P.; Eventräume für Catering kosten extra Miete.",
                external_rating=4.5,
                risk_level="low",
                travel_time_from_office_minutes=8,
                address="Ars-Electronica-Straße 1, 4040 Linz",
                website="https://ars.electronica.art/center/de/deepspace/",
                provider="Ars Electronica Linz",
                phone="073272720",
                email="center@ars.electronica.art",
            ),
            dict(
                title="Segway Tour: Linz schwebend entdecken",
                category=EventCategory.action,
                tags=["segway", "outdoor", "sightseeing", "teambuilding"],
                location_region="OOE",
                est_price_pp=79,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="summer",
                short_description="Geführte Segway-Tour durch Linz und Umgebung – entspannt gleiten statt gehen.",
                long_description="Nach einer kurzen Einschulung schwebt ihr gemeinsam auf Segways durch Stadt, Donauufer oder Natur und erlebt Linz aus einer neuen Perspektive – mit Spaßfaktor und viel Gesprächsstoff fürs Team.",
                physical_intensity=3,
                mental_challenge=1,
                social_interaction_level=3,
                price_comment="Fixpreis pro Person für Tour & Guide (ca. 79 €); kaum Gruppenrabatt, da hohe Equipmentkosten.",
                external_rating=4.8,
                risk_level="medium",
                travel_time_from_office_minutes=6,
                address="Hauptpl. 1, 4020 Linz",
                website="https://linzerschweben.at/",
                provider="Linzer Schweben",
                phone="069910404044",
                email="info@linzerschweben.at",
            ),
            dict(
                title="Mural Harbor: Graffiti Walk & Spray Class",
                category=EventCategory.action,
                tags=["graffiti", "streetart", "kreativ", "führung", "teambuilding", "outdoor"],
                location_region="OOE",
                est_price_pp=35,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="summer",
                short_description="Graffiti-Rundgang im Linzer Hafen mit Möglichkeit zum selbst Sprayen.",
                long_description="Ihr erkundet die Graffiti-Freiluftgalerie im Hafen, erfahrt Hintergründe zu Kunstwerken und Stilrichtungen und könnt im Crashkurs selbst zur Spraydose greifen – kreatives Teamerlebnis mit Erinnerungsfaktor.",
                physical_intensity=3,
                mental_challenge=1,
                social_interaction_level=3,
                price_comment="Nur Führung ca. 15 €; das volle Paket \"Walk & Spray\" (Workshop) kommt auf ca. 35 € p.P.",
                external_rating=4.7,
                risk_level="low",
                travel_time_from_office_minutes=6,
                address="Mural Harbor, Regensburger Str. 2, 4020 Linz",
                website="https://muralharbor.at/tickets/",
                provider="Verein Mural Harbor",
                phone="06646564619",
                email="info@muralharbor.at",
            ),
            dict(
                title="Stahlwelt Linz: Werkstour & Industriekultur",
                category=EventCategory.relax,
                tags=["industrie", "führung", "technik", "lernen", "teambuilding"],
                location_region="OOE",
                est_price_pp=22,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Werksführung mit Blick in die moderne Stahlproduktion und den größten Industriestandort Österreichs.",
                long_description="Mit Guides und Multimediabussen fahrt ihr über das Werksgelände, seht Anlagen aus nächster Nähe und lernt die Reise vom Rohstoff bis zum fertigen Stahl kennen – spannend für technikaffine Teams.",
                physical_intensity=2,
                mental_challenge=1,
                social_interaction_level=2,
                price_comment="Werkstour inkl. Bustransfer ca. 22 €; Mittagessen in der Kantine oder Catering ist extra zu kalkulieren.",
                external_rating=4.6,
                risk_level="low",
                travel_time_from_office_minutes=7,
                address="voestalpine-Straße, 4020 Linz",
                website="https://www.voestalpine.com/stahlwelt/",
                provider="voestalpine Stahlwelt",
                phone="050304158900",
                email="anmeldung.stahlwelt@voestalpine.com",
            ),
            dict(
                title="Stefan's Stubm: Kulinarik & Gemütlichkeit",
                category=EventCategory.food,
                tags=["restaurant", "österreichische-küche", "essen", "gemütlich", "teamevent"],
                location_region="OOE",
                est_price_pp=40,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Österreichische Küche in gemütlicher Stubn-Atmosphäre.",
                long_description="In der warmen Wirtshaus-Atmosphäre genießt ihr traditionelle Speisen, regionale Produkte und viel Gemütlichkeit – ideal für gesellige Teamessen und kleinere Feiern.",
                physical_intensity=1,
                mental_challenge=1,
                social_interaction_level=4,
                price_comment="Reiner Verzehrwert; für ein 3-Gänge-Menü inkl. Getränke solltet ihr mit ca. 40–50 € p.P. rechnen.",
                external_rating=4.6,
                risk_level="low",
                travel_time_from_office_minutes=2,
                address="Garnisonstraße 30, 4020 Linz",
                website="https://www.stubm.at/",
                provider="Stefan's Stubm",
                phone="0732770555",
                email="office@stefans-stubm.at",
            ),
            dict(
                title="Il Teatro: Italienischer Abend fürs Team",
                category=EventCategory.food,
                tags=["restaurant", "italienisch", "pizza", "pasta", "teamevent"],
                location_region="OOE",
                est_price_pp=35,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Italienisches Restaurant mit Pizza, Pasta und mediterranem Flair.",
                long_description="Bei Antipasti, Pasta und Pizza sitzt ihr gemeinsam in entspanntem Ambiente und könnt das Team bei gutem Essen näher zusammenbringen – vom Business-Lunch bis zum Abendessen.",
                physical_intensity=1,
                mental_challenge=1,
                social_interaction_level=4,
                price_comment="Pizza/Pasta ist günstiger (~25 € inkl. Drink); bei Fleisch/Fisch und Wein eher 40–50 € p.P.",
                external_rating=4.5,
                risk_level="low",
                travel_time_from_office_minutes=6,
                address="Hamerlingstraße 46, 4020 Linz",
                website="https://www.ilteatro.at/",
                provider="Ristorante Il Teatro",
                phone="0732662580",
                email="office@ilteatro.at",
            ),
            dict(
                title="Das Josef: Der Linzer Gastro-Klassiker",
                category=EventCategory.food,
                tags=["restaurant", "wirtshaus", "bar", "österreichische-küche", "teamevent"],
                location_region="OOE",
                est_price_pp=35,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Modernes Wirtshaus mit großer Speise- und Getränkekarte im Zentrum von Linz.",
                long_description="Zeitgemäße Wirtshausküche, viele Bier- und Weinoptionen und lebendige Atmosphäre machen das JOSEF zur vielseitigen Location für Teamdinner, Afterwork oder Stammtisch.",
                physical_intensity=1,
                mental_challenge=1,
                social_interaction_level=4,
                price_comment="À la carte Verzehr typischerweise 30–40 €; Buffet-Optionen für große geschlossene Gruppen möglich.",
                external_rating=4.1,
                risk_level="low",
                travel_time_from_office_minutes=5,
                address="Landstraße 49, 4020 Linz",
                website="https://josef.eu/",
                provider="Josef Gastro GmbH",
                phone="0732773165",
                email="gastronomie@josef.eu",
            ),
            dict(
                title="PAULs am Dom: Stylisches Dinner & Drinks",
                category=EventCategory.food,
                tags=["restaurant", "burger", "steak", "bar", "teamevent"],
                location_region="OOE",
                est_price_pp=50,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Stylishes Restaurant mit kreativer Küche und entspannter Bar-Atmosphäre.",
                long_description="Zwischen Burgern, Steaks, Bowls und modernen Klassikern findet jede:r etwas – kombiniert mit Drinks und urbanem Ambiente eine gute Wahl für lockere Firmenessen.",
                physical_intensity=1,
                mental_challenge=1,
                social_interaction_level=4,
                price_comment="Gehobenes Preisniveau; für Steaks/Burger plus Cocktails liegt man schnell bei 50 €+ p.P.",
                external_rating=4.4,
                risk_level="low",
                travel_time_from_office_minutes=8,
                address="Domplatz 3, 4020 Linz",
                website="https://www.pauls-linz.at/",
                provider="PAULS",
                phone="0732783338",
                email="office@pauls-linz.at",
            ),
            dict(
                title="Weinstadl Urfahr: Uriges Dinner & Wein",
                category=EventCategory.food,
                tags=["heuriger", "restaurant", "wein", "österreichische-küche", "teamevent"],
                location_region="OOE",
                est_price_pp=45,
                min_participants=1,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="summer",
                short_description="Gemütlicher Weinstadl mit regionaler Küche und schöner Weinauswahl.",
                long_description="In uriger Atmosphäre genießt ihr bodenständige Speisen, Jausen und passende Weine – perfekt für ein entspanntes, geselliges Beisammensein abseits des Büroalltags.",
                physical_intensity=1,
                mental_challenge=1,
                social_interaction_level=4,
                price_comment="Typischer Heurigen-Konsum oder \"Reindl-Essen\" kommt auf ca. 35–45 € inkl. Weinbegleitung.",
                external_rating=4.5,
                risk_level="low",
                travel_time_from_office_minutes=9,
                address="Griesmayrstraße 18, 4040 Linz",
                website="https://weinstadl-urfahr.eatbu.com/?lang=de",
                provider="Weinstadl Urfahr",
                phone="0732730620",
                email="office@weinstadl-urfahr.at",
            ),
            dict(
                title="Eisstockschießen & Bratl: Winter-Teamevent",
                category=EventCategory.action,
                tags=["eisstockschiessen", "winter", "sport", "teambuilding", "outdoor"],
                location_region="OOE",
                est_price_pp=28,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="winter",
                short_description="„Bratlschießen“ (Eisstockschießen) als lockerer Teamwettbewerb auf dem Eis.",
                long_description="In Teams tretet ihr beim Eisstockschießen gegeneinander an, feuert euch an, lacht über knappe Entscheidungen und erlebt spielerische Spannung – ein winterliches Teamevent mit Humor.",
                physical_intensity=3,
                mental_challenge=1,
                social_interaction_level=4,
                price_comment="Bahnmiete (geteilt) + Leihstock ca. 10 €; das klassische \"Bratl in der Rein\" danach kostet ca. 18–20 € p.P.",
                external_rating=4.5,
                risk_level="low",
                travel_time_from_office_minutes=6,
                address="Untere Donaulände 11, 4020 Linz",
                website="https://www.linzag.at/portal/de/privatkunden/freizeit/eissport/eisstockschiessen",
                provider="LINZ AG (Parkbad)",
                phone="073234006630",
                email="sport@linzag.at",
            ),
            dict(
                title="Hollywood Megaplex: Privates Kino-Event",
                category=EventCategory.relax,
                tags=["kino", "eventlocation", "präsentation", "teamevent", "indoor"],
                location_region="OOE",
                est_price_pp=25,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Exklusiv angemieteter Kinosaal für Film, Präsentation oder Firmenfeier.",
                long_description="Ob gemeinsamer Kinofilm, Produktpräsentation oder Jahresrückblick – im eigenen Saal mit großer Leinwand, Popcorn und Kinofeeling schafft ihr einen besonderen Rahmen für euer Event.",
                physical_intensity=1,
                mental_challenge=1,
                social_interaction_level=3,
                price_comment="Kinoticket + Popcorn/Drink-Menü ca. 20–25 €; Saalmiete variiert je nach Uhrzeit/Film stark.",
                external_rating=4.5,
                risk_level="low",
                travel_time_from_office_minutes=14,
                address="Plus-Kauf-Straße 7, 4061 Pasching",
                website="https://www.megaplex.at/inhalt/kino-zum-mieten",
                provider="Hollywood Megaplex",
                phone="0722963500",
                email="pasching@megaplex.at",
            ),
            dict(
                title="Cocktail-Kurs im Lennox: Mix it up Team!",
                category=EventCategory.party,
                tags=["cocktailkurs", "bar", "mixology", "teambuilding", "indoor"],
                location_region="OOE",
                est_price_pp=59,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Geführter Cocktailkurs mit Profibarkeepern – shaken, rühren, verkosten.",
                long_description="Ihr lernt die Basics der Cocktailkunst, mixt gemeinsam verschiedene Drinks (auch alkoholfrei) und könnt dabei in entspannter Bar-Atmosphäre viel Spaß haben und das Team besser vernetzen.",
                physical_intensity=2,
                mental_challenge=1,
                social_interaction_level=4,
                price_comment="Fixpreis für den Workshop (inkl. Mixen & Trinken der Cocktails); keine versteckten Kosten.",
                external_rating=4.8,
                risk_level="low",
                travel_time_from_office_minutes=6,
                address="Marienstraße 2a, 4020 Linz",
                website="https://www.lennox.at/events/cocktailkurse/",
                provider="Lennox Bar",
                phone="06644104100",
                email="bar@lennox.at",
            ),
            dict(
                title="ÄNGUS Downtown: Bestes Steak-Dinner Linz",
                category=EventCategory.food,
                tags=["restaurant", "steak", "grill", "teamevent"],
                location_region="OOE",
                est_price_pp=60,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Steak- und Grillrestaurant im Zentrum – Fokus auf hochwertigem Fleisch.",
                long_description="Saftige Steaks, Burger und Beilagen in modernem Ambiente: Hier wird Fleischliebe großgeschrieben und euer Teamdinner zum herzhaften Genusserlebnis.",
                physical_intensity=1,
                mental_challenge=1,
                social_interaction_level=4,
                price_comment="Premium Steakhouse; für Vorspeise, Steak und guten Wein muss man mit 70–90 € p.P. kalkulieren.",
                external_rating=4.7,
                risk_level="low",
                travel_time_from_office_minutes=8,
                address="Pfarrpl. 13, 4020 Linz",
                website="https://xn--ngus-koa.at/",
                provider="ÄNGUS Downtown",
                phone="0732771515",
                email="restaurant@aengus.at",
            ),
            dict(
                title="Glorious Bastards: Pizza, Grill & Vibes",
                category=EventCategory.food,
                tags=["restaurant", "steak", "burger", "pizza", "craft-beer", "teamevent"],
                location_region="OOE",
                est_price_pp=40,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Stylishes Meat-&-Pizza-Konzept mit offener Küche und Industrial-Charme.",
                long_description="Dry-Aged-Steaks, Holzofenpizza und Craft Beer treffen auf laute, lebendige Stimmung – ideal für Teams, die es modern, locker und etwas lauter mögen.",
                physical_intensity=1,
                mental_challenge=1,
                social_interaction_level=4,
                price_comment="Burger/Pizza-Konzern; mit 2-3 Getränken und Hauptspeise landet man meist bei soliden 35–45 €.",
                external_rating=4.1,
                risk_level="low",
                travel_time_from_office_minutes=7,
                address="Promenade 25, 4020 Linz",
                website="https://glorious-bastards.at/",
                provider="Glorious Bastards",
                phone="0732773322",
                email="linz@glorious-bastards.at",
            ),
            dict(
                title="Bratwurstglöckerl: Linzer Wirtshauskultur",
                category=EventCategory.food,
                tags=["restaurant", "wirtshaus", "grill", "österreichische-küche", "teamevent"],
                location_region="OOE",
                est_price_pp=35,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Traditionsgasthaus mit Fokus auf Bratwürste und deftige Hausmannskost.",
                long_description="In klassischer Wirtshausatmosphäre genießt ihr Grill- und Pfannengerichte, Bier und regionale Schmankerl – perfekt für unkomplizierte, bodenständige Teamabende.",
                physical_intensity=1,
                mental_challenge=1,
                social_interaction_level=4,
                price_comment="Bodenständig; Hauptspeise + Bier + Kaffee kommt meist auf faire 30–35 € p.P.",
                external_rating=4.5,
                risk_level="low",
                travel_time_from_office_minutes=9,
                address="Angerholzerweg 38, 4020 Linz",
                website="https://www.bratwurstgloeckerl.at/",
                provider="Bratwurstglöckerl",
                phone="0732779388",
                email="office@bratwurstgloeckerl.at",
            ),
            dict(
                title="Stadtliebe Linz: Urbanes Wirtshaus-Event",
                category=EventCategory.food,
                tags=["restaurant", "bar", "brunch", "modern", "teamevent"],
                location_region="OOE",
                est_price_pp=40,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Trendige Mischung aus Restaurant, Bar und Café mitten in Linz.",
                long_description="Von Frühstück und Brunch über kreative Speisen bis hin zu Cocktails am Abend – die Stadtliebe bietet einen flexiblen Rahmen für Teamtreffen zu fast jeder Tageszeit.",
                physical_intensity=1,
                mental_challenge=1,
                social_interaction_level=4,
                price_comment="Modernes Wirtshaus; Menüs für Gruppen ab ca. 35 €, mit Getränken realistisch 40–50 €.",
                external_rating=4.1,
                risk_level="low",
                travel_time_from_office_minutes=5,
                address="Landstraße 31, 4020 Linz",
                website="https://www.stadtliebe.at/",
                provider="Stadtliebe Linz",
                phone="0732770605",
                email="office@stadtliebe.at",
            ),
            dict(
                title="Wia z'haus Lehner: Schmankerl & Ausblick",
                category=EventCategory.food,
                tags=["wirtshaus", "österreichische-küche", "traditionell", "teamevent"],
                location_region="OOE",
                est_price_pp=35,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Traditionelles Wirtshaus mit regionaler Küche und viel Gemütlichkeit.",
                long_description="Holzvertäfelung, große Portionen und herzlicher Service sorgen für klassisches Wirtshausgefühl – ideal für Teams, die es ehrlich, bodenständig und ohne Schnickschnack mögen.",
                physical_intensity=1,
                mental_challenge=1,
                social_interaction_level=4,
                price_comment="Klassischer Verzehr; \"Bratl\"-Essen für Gruppen oft günstiger, à la carte ca. 35 € inkl. Getränke.",
                external_rating=4.4,
                risk_level="low",
                travel_time_from_office_minutes=8,
                address="Harbacher Str. 38, 4040 Linz",
                website="https://www.wiazhaus-lehner.at/",
                provider="Wia z'haus Lehner",
                phone="0732730510",
                email="gasthaus@wiazhaus-lehner.at",
            ),
            dict(
                title="Zur Eisernen Hand: Tradition & Genuss",
                category=EventCategory.food,
                tags=["gasthaus", "österreichische-küche", "traditionell", "teamevent"],
                location_region="OOE",
                est_price_pp=35,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="summer",
                short_description="Gutbürgerliches Gasthaus mit klassischen Speisen und saisonalen Gerichten.",
                long_description="In entspannter Atmosphäre genießt ihr regionale Küche, Stammtischflair und viel Platz für Gespräche – geeignet für gemütliche Teamessen oder Familienfeiern.",
                physical_intensity=1,
                mental_challenge=1,
                social_interaction_level=4,
                price_comment="Uriges Wirtshaus; Schnitzel/Bratl + Getränke liegen im Schnitt bei 30–40 € p.P.",
                external_rating=4.6,
                risk_level="low",
                travel_time_from_office_minutes=3,
                address="Eisenhandstraße 43, 4020 Linz",
                website="https://www.gasthaus-eisernehand.at/",
                provider="Gasthaus Eiserne Hand",
                phone="0732773335",
                email="gasthaus@eisernehand.at",
            ),
            dict(
                title="Rotax MAX Dome: High-Speed E-Kart Action",
                category=EventCategory.action,
                tags=["e-kart", "kartfahren", "action", "indoor", "teambuilding"],
                location_region="OOE",
                est_price_pp=45,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="E-Kart-Action",
                long_description="Auf der modernen Indoor-E-Kartbahn jagt ihr emissionsfrei über die Strecke, fahrt Qualifying und Rennen und kürt am Ende euer Team-Podium – Adrenalin pur, auch bei Schlechtwetter.",
                physical_intensity=5,
                mental_challenge=2,
                social_interaction_level=2,
                price_comment="Renn-Pakete (Training, Quali, Rennen) starten ab ca. 45 €; Premium-Events mit Siegerehrung bis 70 €.",
                external_rating=4.5,
                risk_level="high",
                travel_time_from_office_minutes=5,
                address="Holzstraße 3, 4020 Linz",
                website="https://www.rotaxmaxdome.com/linz/",
                provider="Rotax MAX Dome",
                phone="0732799899",
                email="linz@rotaxmaxdome.com",
            ),
            dict(
                title="Booosters Kartbahn: Rennfeeling für Teams",
                category=EventCategory.action,
                tags=["kartfahren", "action", "eventlocation", "teambuilding", "gastro"],
                location_region="OOE",
                est_price_pp=40,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Kart-Racing + Gastro für bis zu 100 Personen, „Rundum-Service“ für Firmenfeiern",
                long_description="Vom Fahrerbriefing über Rennen bis zur Siegerehrung wird euer Event komplett organisiert; dazu kommen Gastronomie und Aufenthaltsbereiche – ideal für große Gruppen und Firmenfeste mit Racing-Faktor.",
                physical_intensity=5,
                mental_challenge=2,
                social_interaction_level=2,
                price_comment="Gruppen-Grand-Prix (inkl. Qualifying & Rennen) kostet ca. 38–45 € p.P.; Bahn exklusiv mietbar.",
                external_rating=4.3,
                risk_level="high",
                travel_time_from_office_minutes=14,
                address="Im Bäckerfeld 1, 4060 Leonding",
                website="https://booosters.at/",
                provider="Booosters",
                phone="0722921700",
                email="office@booosters.at",
            ),
            dict(
                title="Mission Games: Die Live Game-Show Linz",
                category=EventCategory.action,
                tags=["actiongame", "rätsel", "geschicklichkeit", "teambuilding", "indoor"],
                location_region="OOE",
                est_price_pp=34,
                accessibility_flags=[],
                weather_dependent=False,
                image_url="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
                season="all_year",
                short_description="Indoor-Actionspiel mit vielen Missionräumen, in denen Geschick und Teamwork zählen.",
                long_description="Auf mehreren hundert Quadratmetern warten unterschiedlichste Räume mit Aufgaben zu Reaktion, Geschicklichkeit, Logik und Teamplay – ihr sammelt Punkte, probiert Missionen aus und feuert euch gegenseitig an.",
                physical_intensity=2,
                mental_challenge=5,
                social_interaction_level=5,
                price_comment="Preisstaffelung: Ab 13 Personen ca. 34 € p.P., kleinere Gruppen zahlen etwas mehr (bis 39 €).",
                external_rating=4.9,
                risk_level="low",
                travel_time_from_office_minutes=7,
                address="Hauptstraße 16/1. Stock, 4040 Linz",
                website="https://missiongames.at/",
                provider="Mission Games",
                phone="06606363063",
                email="office@missiongames.at",
            ),
        ],
    }

    for region, items in seeds_by_region.items():
        exists = session.exec(
            select(EventOption).where(EventOption.location_region == region)
        ).first()
        if exists:
            continue
        session.add_all([EventOption(**item) for item in items])
    session.commit()


def _ensure_voting_deadline_column() -> None:
    """Ensure new column exists on sqlite without a full migration system."""
    if not settings.database_url.startswith("sqlite"):
        return
    with engine.begin() as conn:
        cols = conn.exec_driver_sql("PRAGMA table_info(campaign);").fetchall()
        names = {c[1] for c in cols}
        if "voting_deadline" not in names:
            conn.exec_driver_sql("ALTER TABLE campaign ADD COLUMN voting_deadline TIMESTAMP;")


def init_db() -> None:
    """Create database tables. Call this once at startup."""
    from app import models  # noqa: F401 - triggers model registration

    SQLModel.metadata.create_all(bind=engine)
    _ensure_voting_deadline_column()
    with Session(engine) as session:
        seed_event_options(session)


def get_session() -> Generator[Session, None, None]:
    with Session(engine) as session:
        yield session


@contextmanager
def session_scope() -> Generator[Session, None, None]:
    session = Session(engine)
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()
